In [169]:
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [170]:
df = pd.read_csv('processed.cleveland.data', header=None)
df.columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']
df = df.replace('?', np.nan)
df['ca'] = df['ca'].astype(float)
df['thal'] = df['thal'].astype(float)
df = df.fillna(df.mean())
df['num'] = df['num'].replace([2, 3, 4], 1)
df.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    1  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

In [171]:
x = df.iloc[:,0:13]
y = df.iloc[:,13]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.8, random_state = 1)

In [172]:
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [173]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86       133
           1       0.86      0.78      0.82       110

    accuracy                           0.84       243
   macro avg       0.85      0.84      0.84       243
weighted avg       0.84      0.84      0.84       243



In [174]:
x_test[0:5]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
204  43.0  1.0  4.0     110.0  211.0  0.0      0.0    161.0    0.0      0.0   
159  68.0  1.0  3.0     118.0  277.0  0.0      0.0    151.0    0.0      1.0   
219  59.0  1.0  4.0     138.0  271.0  0.0      2.0    182.0    0.0      0.0   
174  64.0  1.0  4.0     145.0  212.0  0.0      2.0    132.0    0.0      2.0   
184  60.0  0.0  4.0     158.0  305.0  0.0      2.0    161.0    0.0      0.0   

     slope   ca  thal  
204    1.0  0.0   7.0  
159    1.0  1.0   7.0  
219    1.0  0.0   3.0  
174    2.0  2.0   6.0  
184    1.0  0.0   3.0

In [175]:
y_pred[0:5]

array([0, 0, 0, 1, 0], dtype=int64)

In [176]:
y_test[0:5]

204    0
159    0
219    0
174    1
184    1
Name: num, dtype: int64

In [185]:
# sex: sex (1 = male; 0 = female)
x_train_sex = x_train.iloc[:,1:2]
model = GaussianNB()
model.fit(x_train_sex, y_train)
y_pred = model.predict_proba([[1]])
print('output format: [[proba_of_absence proba_of_presence]]')
print('male:')
print(y_pred)
y_pred = model.predict_proba([[0]])
print('female:')
print(y_pred)

output format: [[proba_of_absence proba_of_presence]]
male:
[[0.38758467 0.61241533]]
female:
[[0.81863999 0.18136001]]
