In [2]:
from sklearn import preprocessing
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
wine = datasets.load_wine()

In [4]:
print(wine.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [5]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:
X_train, X_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.3,random_state=109)

In [7]:
print(X_train, y_train)

[[1.323e+01 3.300e+00 2.280e+00 ... 5.600e-01 1.510e+00 6.750e+02]
 [1.384e+01 4.120e+00 2.380e+00 ... 5.700e-01 1.640e+00 4.800e+02]
 [1.220e+01 3.030e+00 2.320e+00 ... 6.600e-01 1.830e+00 5.100e+02]
 ...
 [1.362e+01 4.950e+00 2.350e+00 ... 9.100e-01 2.050e+00 5.500e+02]
 [1.336e+01 2.560e+00 2.350e+00 ... 7.000e-01 2.470e+00 7.800e+02]
 [1.439e+01 1.870e+00 2.450e+00 ... 1.020e+00 3.580e+00 1.290e+03]] [2 2 2 2 1 0 2 1 2 1 1 0 1 0 2 2 1 1 0 1 0 1 2 1 2 0 0 0 1 0 0 2 1 2 1 1 2
 0 1 2 1 0 0 2 1 0 2 1 1 0 1 1 2 1 1 1 0 2 0 1 1 0 1 1 1 1 2 1 1 1 1 0 0 0
 1 1 2 2 1 1 0 1 2 2 1 2 2 1 1 2 2 2 0 0 0 0 0 1 1 1 0 2 0 1 2 0 0 1 0 1 1
 2 1 2 0 0 0 1 0 0 1 2 2 0]


In [8]:
print(X_test, y_test)

[[1.330000e+01 1.720000e+00 2.140000e+00 1.700000e+01 9.400000e+01
  2.400000e+00 2.190000e+00 2.700000e-01 1.350000e+00 3.950000e+00
  1.020000e+00 2.770000e+00 1.285000e+03]
 [1.293000e+01 3.800000e+00 2.650000e+00 1.860000e+01 1.020000e+02
  2.410000e+00 2.410000e+00 2.500000e-01 1.980000e+00 4.500000e+00
  1.030000e+00 3.520000e+00 7.700000e+02]
 [1.221000e+01 1.190000e+00 1.750000e+00 1.680000e+01 1.510000e+02
  1.850000e+00 1.280000e+00 1.400000e-01 2.500000e+00 2.850000e+00
  1.280000e+00 3.070000e+00 7.180000e+02]
 [1.253000e+01 5.510000e+00 2.640000e+00 2.500000e+01 9.600000e+01
  1.790000e+00 6.000000e-01 6.300000e-01 1.100000e+00 5.000000e+00
  8.200000e-01 1.690000e+00 5.150000e+02]
 [1.421000e+01 4.040000e+00 2.440000e+00 1.890000e+01 1.110000e+02
  2.850000e+00 2.650000e+00 3.000000e-01 1.250000e+00 5.240000e+00
  8.700000e-01 3.330000e+00 1.080000e+03]
 [1.311000e+01 1.010000e+00 1.700000e+00 1.500000e+01 7.800000e+01
  2.980000e+00 3.180000e+00 2.600000e-01 2.280000e+00

In [9]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
y_pred = model.predict(X_test)
print(y_pred)

[0 0 1 2 0 1 0 0 1 0 2 2 2 2 0 1 1 0 0 1 2 1 0 2 0 0 1 2 0 1 2 1 1 0 1 1 0
 2 2 0 2 1 0 0 0 2 2 0 1 1 2 0 0 2]


In [11]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9074074074074074
